import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#f6f3ec",
  },
  screenCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: 20,
    backgroundColor: "#f6f3ec",
  },
  container: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 28,
    gap: 16,
  },
  screenHeader: {
    gap: 12,
  },
  screenHeaderCopy: {
    gap: 6,
  },
  kicker: {
    fontSize: 12,
    letterSpacing: 1.1,
    textTransform: "uppercase",
    color: "#5d7282",
    fontWeight: "700",
  },
  heading: {
    fontSize: 30,
    lineHeight: 34,
    color: "#16232d",
    fontWeight: "800",
  },
  bodyText: {
    color: "#2f404c",
    fontSize: 15,
    lineHeight: 22,
  },
  helperText: {
    color: "#5e6f7b",
    fontSize: 13,
    lineHeight: 19,
  },
  errorText: {
    color: "#9b2d20",
    fontSize: 13,
    lineHeight: 18,
  },
  label: {
    fontSize: 13,
    color: "#435562",
    fontWeight: "700",
  },
  fieldGroup: {
    gap: 8,
  },
  sectionCard: {
    borderRadius: 18,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d9e1e5",
    overflow: "hidden",
  },
  sectionCardHeader: {
    paddingHorizontal: 16,
    paddingTop: 15,
    gap: 4,
  },
  sectionCardTitle: {
    color: "#152630",
    fontWeight: "800",
    fontSize: 17,
  },
  sectionCardBody: {
    padding: 16,
    gap: 12,
  },
  emptyState: {
    gap: 10,
  },
  statusBanner: {
    borderRadius: 14,
    backgroundColor: "#e8f0f5",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#cad8e2",
  },
  statusBannerSuccess: {
    backgroundColor: "#e4f4ea",
    borderColor: "#c0ddc9",
  },
  statusBannerError: {
    backgroundColor: "#f9e7e3",
    borderColor: "#efc8c0",
  },
  statusBannerText: {
    color: "#23445a",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
  },
  statusBannerTextSuccess: {
    color: "#215338",
  },
  statusBannerTextError: {
    color: "#8e2b1f",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccd6dc",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 11,
    backgroundColor: "#fbfcfd",
    color: "#1e2e38",
    fontSize: 15,
  },
  pickerField: {
    borderWidth: 1,
    borderColor: "#ccd6dc",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 13,
    backgroundColor: "#fbfcfd",
  },
  pickerFieldValue: {
    color: "#1e2e38",
    fontSize: 15,
    fontWeight: "600",
  },
  pickerFieldPlaceholder: {
    color: "#7a848c",
    fontSize: 15,
  },
  textArea: {
    minHeight: 104,
    textAlignVertical: "top",
  },
  primaryButton: {
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: "#164f73",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonDisabled: {
    backgroundColor: "#8aa0b0",
  },
  primaryButtonText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 14,
  },
  secondaryButton: {
    borderRadius: 12,
    paddingVertical: 11,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#9cb0bf",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f7fafc",
  },
  secondaryButtonDisabled: {
    opacity: 0.55,
  },
  secondaryButtonText: {
    color: "#234760",
    fontWeight: "700",
    fontSize: 14,
  },
  stickyActionBar: {
    paddingTop: 6,
    gap: 10,
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  segmentedChip: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#d1dae0",
    backgroundColor: "#f8fafb",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  segmentedChipSelected: {
    borderColor: "#164f73",
    backgroundColor: "#e7f1f8",
  },
  segmentedChipText: {
    color: "#425968",
    fontSize: 13,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  segmentedChipTextSelected: {
    color: "#0f4261",
  },
  tag: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#d1dae0",
    backgroundColor: "#f8fafb",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  tagSelected: {
    borderColor: "#164f73",
    backgroundColor: "#e7f1f8",
  },
  tagText: {
    color: "#425968",
    fontSize: 13,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  tagTextSelected: {
    color: "#0f4261",
  },
  counterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  counterButton: {
    width: 38,
    height: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#cad5dc",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fbfcfd",
  },
  counterButtonText: {
    fontSize: 18,
    color: "#213540",
    fontWeight: "700",
  },
  counterValue: {
    minWidth: 40,
    textAlign: "center",
    fontSize: 17,
    color: "#1d2c36",
    fontWeight: "800",
  },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  metricCard: {
    minWidth: "47%",
    flexGrow: 1,
    borderWidth: 1,
    borderColor: "#dbe4e8",
    borderRadius: 12,
    padding: 11,
    backgroundColor: "#fbfcfd",
    gap: 4,
  },
  metricLabel: {
    color: "#5b7080",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    fontWeight: "700",
  },
  metricValue: {
    color: "#1d2f39",
    fontSize: 16,
    fontWeight: "800",
  },
  listItem: {
    gap: 10,
  },
  subtleBlock: {
    gap: 6,
    borderWidth: 1,
    borderColor: "#dde5e9",
    borderRadius: 12,
    padding: 11,
    backgroundColor: "#fbfcfd",
  },
  availabilityDayCard: {
    gap: 10,
    borderWidth: 1,
    borderColor: "#dbe4e8",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#ffffff",
  },
  availabilityDayHeader: {
    gap: 2,
  },
  availabilityWindowCard: {
    gap: 8,
    borderWidth: 1,
    borderColor: "#e3eaee",
    borderRadius: 10,
    padding: 10,
    backgroundColor: "#fbfcfd",
  },
  weekStructureList: {
    gap: 8,
  },
  weekStructureRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: "#dde6ea",
    borderRadius: 10,
    backgroundColor: "#fbfcfd",
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  weekStructureWeek: {
    width: 30,
    color: "#2f4554",
    fontWeight: "800",
    fontSize: 12,
  },
  weekStructurePercent: {
    width: 48,
    color: "#1f4f6e",
    fontWeight: "700",
    fontSize: 12,
  },
  weekStructureEmphasis: {
    flex: 1,
    color: "#314650",
    fontSize: 12,
  },
  weekList: {
    gap: 8,
  },
  weekListRow: {
    gap: 5,
    borderWidth: 1,
    borderColor: "#dbe4e8",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#fbfcfd",
  },
  weekListRowActive: {
    borderColor: "#164f73",
    backgroundColor: "#eef6fb",
  },
  weekListHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  weekListTitle: {
    color: "#223540",
    fontWeight: "800",
    fontSize: 14,
  },
  weekBadge: {
    color: "#0f4261",
    backgroundColor: "#d8ebf7",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  weekDetailBlock: {
    gap: 10,
    paddingTop: 4,
  },
  weekDetailHeading: {
    color: "#17242d",
    fontWeight: "800",
    fontSize: 20,
  },
  workoutList: {
    gap: 10,
  },
  workoutCard: {
    gap: 8,
    borderWidth: 1,
    borderColor: "#dbe4e8",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#fbfcfd",
  },
  workoutCardActive: {
    borderColor: "#164f73",
    backgroundColor: "#eef6fb",
  },
  workoutTitle: {
    color: "#1d2f39",
    fontWeight: "800",
    fontSize: 15,
  },
  segmentList: {
    gap: 6,
    paddingTop: 2,
  },
  statusRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    overflow: "hidden",
  },
  statusBadgeMatched: {
    color: "#0f5132",
    backgroundColor: "#d9f3e6",
  },
  statusBadgeNeedsReview: {
    color: "#7a4d04",
    backgroundColor: "#f8ebc8",
  },
  statusBadgeUnmatched: {
    color: "#6b3644",
    backgroundColor: "#f3dde5",
  },
  historyWorkoutBlock: {
    borderWidth: 1,
    borderColor: "#dde6ea",
    borderRadius: 12,
    backgroundColor: "#fbfcfd",
    padding: 12,
    gap: 8,
  },
  historyWorkoutTitle: {
    color: "#1b2c36",
    fontWeight: "800",
    fontSize: 15,
  },
  historyIntervalList: {
    borderTopWidth: 1,
    borderTopColor: "#e4ebef",
    marginTop: 2,
    gap: 8,
    paddingTop: 8,
  },
  historyChainBlock: {
    borderWidth: 1,
    borderColor: "#e3eaee",
    borderRadius: 10,
    padding: 10,
    gap: 6,
    backgroundColor: "#ffffff",
  },
  historyChainTitle: {
    color: "#1f2f38",
    fontWeight: "800",
    fontSize: 13,
  },
  historyIntervalRow: {
    flexDirection: "row",
    gap: 8,
    paddingTop: 2,
  },
  historyIntervalLabel: {
    color: "#344d5d",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    minWidth: 48,
  },
  historyIntervalValue: {
    color: "#2f404c",
    fontSize: 14,
  },
  executionBlock: {
    gap: 12,
    paddingTop: 8,
  },
  executionHeading: {
    color: "#1d2f39",
    fontWeight: "800",
    fontSize: 16,
  },
  executionSection: {
    gap: 10,
  },
  executionSectionTitle: {
    color: "#1f3340",
    fontWeight: "800",
    fontSize: 14,
  },
  candidateList: {
    gap: 10,
  },
  candidateCard: {
    gap: 8,
    borderWidth: 1,
    borderColor: "#dbe4e8",
    borderRadius: 12,
    padding: 10,
    backgroundColor: "#ffffff",
  },
  candidateTitle: {
    color: "#1d2f39",
    fontWeight: "800",
    fontSize: 14,
  },
  chatBubble: {
    borderRadius: 14,
    padding: 12,
    gap: 6,
    borderWidth: 1,
  },
  chatBubbleCoach: {
    backgroundColor: "#fbfcfd",
    borderColor: "#dde6ea",
  },
  chatBubbleUser: {
    backgroundColor: "#e8f1f7",
    borderColor: "#b8d0df",
  },
  chatMeta: {
    color: "#516775",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  chatBody: {
    color: "#22333d",
    fontSize: 15,
    lineHeight: 21,
  },
  timeInputRow: {
    flexDirection: "row",
    gap: 10,
  },
  timeInputBlock: {
    flex: 1,
    gap: 6,
  },
  pickerSheetOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(18, 27, 33, 0.24)",
  },
  pickerSheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  pickerSheetCard: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: "#ffffff",
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 28,
    gap: 14,
    borderTopWidth: 1,
    borderColor: "#d9e1e5",
  },
  pickerSheetHeader: {
    gap: 12,
  },
  pickerSheetActions: {
    flexDirection: "row",
    gap: 8,
  },
  tabContent: {
    flex: 1,
  },
  tabBar: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "#d6ddd7",
    backgroundColor: "#ffffff",
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    gap: 2,
  },
  tabButtonActive: {
    backgroundColor: "#e4f0f7",
  },
  tabButtonText: {
    fontSize: 12,
    color: "#526575",
    fontWeight: "600",
  },
  tabButtonTextActive: {
    color: "#134c6e",
    fontWeight: "800",
  },
});
