import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#f7f4ed",
  },
  screenCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: "#f7f4ed",
  },
  container: {
    padding: 20,
    gap: 16,
  },
  kicker: {
    fontSize: 13,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: "#4f6a7e",
    fontWeight: "600",
  },
  heading: {
    fontSize: 30,
    lineHeight: 34,
    color: "#17242d",
    fontWeight: "700",
  },
  helperText: {
    color: "#4e606d",
    fontSize: 14,
  },
  errorText: {
    color: "#9b2d20",
    fontSize: 13,
  },
  panel: {
    borderRadius: 14,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d5ddd8",
    overflow: "hidden",
  },
  panelTitle: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#e8efe9",
    color: "#1f2f28",
    fontWeight: "600",
  },
  panelBody: {
    padding: 14,
    gap: 12,
  },
  listItem: {
    gap: 10,
    paddingVertical: 6,
  },
  weekStructureList: {
    gap: 6,
  },
  weekStructureRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: "#dde6ea",
    borderRadius: 8,
    backgroundColor: "#fbfcfd",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  weekStructureWeek: {
    width: 30,
    color: "#2f4554",
    fontWeight: "700",
    fontSize: 12,
  },
  weekStructurePercent: {
    width: 42,
    color: "#1f4f6e",
    fontWeight: "600",
    fontSize: 12,
  },
  weekStructureEmphasis: {
    flex: 1,
    color: "#2f404c",
    fontSize: 12,
  },
  historyWorkoutBlock: {
    borderWidth: 1,
    borderColor: "#dde6ea",
    borderRadius: 10,
    backgroundColor: "#fbfcfd",
    padding: 12,
    gap: 8,
  },
  historyWorkoutTitle: {
    color: "#1b2c36",
    fontWeight: "700",
    fontSize: 15,
  },
  historyIntervalList: {
    borderTopWidth: 1,
    borderTopColor: "#e4ebef",
    marginTop: 2,
    gap: 8,
    paddingTop: 8,
  },
  historyChainBlock: {
    borderWidth: 1,
    borderColor: "#e3eaee",
    borderRadius: 8,
    padding: 10,
    gap: 6,
    backgroundColor: "#ffffff",
  },
  historyChainTitle: {
    color: "#1f2f38",
    fontWeight: "700",
    fontSize: 13,
  },
  historyIntervalRow: {
    paddingTop: 2,
    gap: 3,
  },
  historyIntervalLabel: {
    color: "#344d5d",
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  historyIntervalValue: {
    color: "#2f404c",
    fontSize: 14,
  },
  chatBubble: {
    borderRadius: 12,
    padding: 12,
    gap: 6,
    borderWidth: 1,
  },
  chatBubbleCoach: {
    backgroundColor: "#fbfcfd",
    borderColor: "#dde6ea",
  },
  chatBubbleUser: {
    backgroundColor: "#e8f1f7",
    borderColor: "#b8d0df",
  },
  chatMeta: {
    color: "#516775",
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  chatBody: {
    color: "#22333d",
    fontSize: 15,
    lineHeight: 21,
  },
  bodyText: {
    color: "#2f404c",
    fontSize: 15,
    lineHeight: 22,
  },
  label: {
    fontSize: 13,
    color: "#435562",
    fontWeight: "600",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ced8de",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#fbfcfc",
    color: "#1f2f38",
  },
  textArea: {
    minHeight: 90,
    textAlignVertical: "top",
  },
  primaryButton: {
    borderRadius: 10,
    paddingVertical: 11,
    backgroundColor: "#165177",
    alignItems: "center",
  },
  primaryButtonDisabled: {
    backgroundColor: "#7b97ab",
  },
  primaryButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  secondaryButton: {
    borderRadius: 10,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#7391a6",
    alignItems: "center",
    backgroundColor: "#f7fbff",
  },
  secondaryButtonDisabled: {
    opacity: 0.6,
  },
  secondaryButtonText: {
    color: "#1f4f6e",
    fontWeight: "600",
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  tag: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#c6d2da",
    backgroundColor: "#ffffff",
  },
  tagSelected: {
    borderColor: "#165177",
    backgroundColor: "#e5f0f7",
  },
  tagText: {
    color: "#395061",
    fontSize: 13,
  },
  tagTextSelected: {
    color: "#0f4261",
    fontWeight: "600",
  },
  counterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  counterButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#c5d1d9",
    alignItems: "center",
    justifyContent: "center",
  },
  counterButtonText: {
    fontSize: 18,
    color: "#2a3d4a",
  },
  counterValue: {
    minWidth: 36,
    textAlign: "center",
    fontWeight: "600",
    color: "#1d2c36",
  },
  timeInputRow: {
    flexDirection: "row",
    gap: 10,
  },
  timeInputBlock: {
    flex: 1,
    gap: 6,
  },
  tabContent: {
    flex: 1,
  },
  tabBar: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "#d6ddd7",
    backgroundColor: "#ffffff",
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
  },
  tabButtonActive: {
    backgroundColor: "#e4f0f7",
  },
  tabButtonText: {
    fontSize: 12,
    color: "#526575",
    fontWeight: "500",
  },
  tabButtonTextActive: {
    color: "#134c6e",
    fontWeight: "700",
  },
  weekList: {
    gap: 8,
  },
  weekListRow: {
    gap: 4,
    borderWidth: 1,
    borderColor: "#dbe4e8",
    borderRadius: 10,
    padding: 10,
    backgroundColor: "#fbfcfd",
  },
  weekListRowActive: {
    borderColor: "#165177",
    backgroundColor: "#eef6fb",
  },
  weekListHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  weekListTitle: {
    color: "#223540",
    fontWeight: "700",
    fontSize: 14,
  },
  weekBadge: {
    color: "#0f4261",
    backgroundColor: "#d8ebf7",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  weekDetailBlock: {
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: "#e2e9ec",
    paddingTop: 12,
  },
  weekDetailHeading: {
    color: "#17242d",
    fontWeight: "700",
    fontSize: 18,
  },
  workoutList: {
    gap: 10,
  },
  workoutCard: {
    gap: 6,
    borderWidth: 1,
    borderColor: "#dbe4e8",
    borderRadius: 10,
    padding: 12,
    backgroundColor: "#fbfcfd",
  },
  workoutTitle: {
    color: "#1d2f39",
    fontWeight: "700",
    fontSize: 15,
  },
  segmentList: {
    gap: 4,
    paddingTop: 2,
  },
});
